site_name: Rostruct Documentation
site_url: https://richie0866.github.io/Rostruct/
repo_name: richie0866/Rostruct
repo_url: https://github.com/richie0866/Rostruct

theme:
  name: material
  highlightjs: true
  hljs_languages:
      - typescript
      - lua
  palette:
    scheme: slate
    primary: 'Light Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Guide:
    - Setting up: guide/setting-up.md
    - Basic usage: guide/basic-usage.md
    - Examples: guide/examples.md
    - Execution model: guide/execution-model.md
    - File conversion: guide/file-conversion.md
  - API Reference: api-reference.md
  - Scripts using Rostruct: scripts-using-rostruct.md

extra_css:
  - extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
