site_name: Rostruct Documentation
site_url: https://richie0866.github.io/rostruct-ts/
repo_name: richie0866/rostruct-ts
repo_url: https://github.com/richie0866/rostruct-ts

theme:
  name: material
  highlightjs: true
  hljs_languages:
      - typescript
      - lua
  palette:
    scheme: slate
    primary: 'Light Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Guide:
    - Setting up: guide/setting-up.md
    - Basic usage: guide/basic-usage.md
  - API Reference: api-reference.md

extra_css:
- extra.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
