name: Deploy docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
