name: Deploy docs

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Deploy docs
        run: |
          pip install mkdocs-material
          pip install -r docs/requirements.txt
          mkdocs gh-deploy --force
