name: Release

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@master
      with:
        node-version: 14.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install node_modules
      run: |
        npm install -g roblox-ts@latest
        npm install

    - name: Build 
      run: |
        npm run build:out

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        files: out/Rostruct.lua